### PR TITLE
Allow for exit after dump

### PR DESCRIPTION
**Pull request by nVitius**
This patch is a proposal to address #772

### CODE REVIEW

**Comment by nVitius** [comment]
@ShaneHarvey Can you review this please?

**Comment by nVitius** [comment]
@mongodb @durran @edaniels @IanWhalen @justinjmoses @stennie  
Tagging you guys as you're the only public members of the mongodb-labs org. Can we get this merge request reviewed at least? It's been several months since it was opened.

**Comment by edaniels** [comment]
@nvitius I'll make sure we get the right person to respond to you. Sorry for the delay.

**Comment by nVitius** [comment]
Thanks for the quick reply, @edaniels; I appreciate it. Have you been able to find someone to help with this PR?

**Comment by edaniels** [comment]
Yep, it's being looked into but the person responsible for maintaining this is on vacation so it may take a week or so.

**Comment by nVitius** [comment]
@edaniels Any updates on having someone look at this repo? There's a few other merge requests that I think are really important to have merged in as well. Like #781 (required for Mongo 3.6 compatibility)

**Comment by edaniels** [comment]
@nVitius it looks like yougov owns this repo, not MongoDB.

**Comment by nVitius** [comment]
@edaniels I imagine that changed sometime between now and April.
https://web.archive.org/web/20180611020311/https://github.com/mongodb-labs/mongo-connector

The README for this project mentions that it used to be owned by mongodb-labs.
Hopefully, with the change of ownership, pull requests will be reviewed and merged in a more timely manner.

Thanks for following up.

**Comment by nVitius** [comment]
@jaraco @mnowotka 
I made this PR a while ago, when I was using mongo-connector for work. I've since moved to a different company, but I think this functionality could be useful for more people and is still worth merging in. Let me know what you think.

**Comment by jaraco** [comment]
Released as 3.1.0.

**Pull request merged**
